# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      # Assume the role that has access to deploy the application
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/$BUILD_ROLE" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
  build:
    commands:
      - echo "[Deploying]"
      # Clean up resources from non-prod environments
      - make clean-up-environments PROFILE=$PROFILE
      # Clean up ECR repositories with old images
      # - make clean-up-ecr-repositories PROFILE=$PROFILE
