version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/application"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "weekly"
    target-branch: "main"

  # Docker Dependencies
  - package-ecosystem: "docker"
    directory: "/build/docker/tester"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/build/docker/search"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/build/docker/data"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/build/docker/ui"
    schedule:
      interval: "weekly"
    target-branch: "main"

  # Maintain dependencies for TypeScript
  - package-ecosystem: "npm"
    directory: "/application/ui"
    schedule:
      interval: "monthly"
    target-branch: "main"

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/infrastructure/stacks/application"
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: "terraform"
    directory: "/infrastructure/modules/codebuild"
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: "terraform"
    directory: "/infrastructure/stacks/development-and-deployment-tools"
    schedule:
      interval: "monthly"
    target-branch: "main"
