version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "daily"
    target-branch: "main"

  # Docker Dependencies
  - package-ecosystem: "docker"
    directory: "/build/docker/tester"
    schedule:
      interval: "daily"
    target-branch: "main"

  # Maintain dependencies for TypeScript
  - package-ecosystem: "npm"
    directory: "/application/ui"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/infrastructure/stacks/application"
    schedule:
      interval: "monthly"
    target-branch: "main"
