[tool.coverage.run]
omit = ["**/__init__.py", "**/tests/**", "application/conftest.py"]
branch = true

[tool.bandit]
exclude_dirs = ["/tests", "ui"]

[tool.vulture]
make_whitelist = true
paths = ["application"]
exclude = ["application/ui", "application/conftest.py", "application/__init__.py", "**/tests/**"]
sort_by_size = true
ignore_names = ["lambda_handler", "tracer", "logger", "context", "event"]

[tool.pytest.ini_options]
addopts = "--ignore=application/ui --cov=. --cov-report xml --cov-report term-missing"
