apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${PROJECT_ID_TO_REPLACE}_readwrite
  namespace: K8S_APP_NAMESPACE_TO_REPLACE
rules:
  - apiGroups: [""]
    resources:
      [
        "configmaps",
        "events",
        "persistentvolumeclaims",
        "pods",
        "secrets",
        "serviceaccounts",
        "services",
        "pods/log",
        "pods/exec",
      ]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io", "extensions"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["appmesh.k8s.aws"]
    resources:
      [
        "meshes",
        "virtualgateways",
        "virtualnodes",
        "virtualrouters",
        "virtualservices",
      ]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["delete", "get"]
