# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      # Assume the role that has access to test the application
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECDoSCTPipelineBuildRole" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws sts get-caller-identity
      - make -s tester-build
  build:
    commands:
      - echo "[Testing]"
      - echo ENVIRONMENT=$ENVIRONMENT
      - echo PROFILE=$PROFILE
      - make api-integration-tests PROFILE=$PROFILE ENVIRONMENT=$ENVIRONMENT

reports:
  ApiIntegrationTestsReport:
    files:
      - "testresults.json"
    base-directory: $CODEBUILD_SRC_DIR/test/integration
    discard-paths: yes
    file-format: CUCUMBERJSON
