# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      # Install Yarn
      - make pip-install
  build:
    commands:
      # Run unit tests
      - make python-unit-test
