# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Install Yarn
      - npm install --location=global yarn
      # Yarn install and setup for tests
      - make typescript-unit-test-ci-setup
  build:
    commands:
      # Run unit tests
      - make typescript-unit-test
reports:
  typescript-unit-tests:
    files:
      - junit.xml
    base-directory: $CODEBUILD_SRC_DIR/application/ui
    discard-paths: yes
    file-format: JUNITXML
