# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - yum install -y openssl
      - cp /etc/pki/tls/openssl.cnf /etc/ssl/openssl.cnf
      # Build certificates
      - make ssl-generate-certificate-project
  build:
    commands:
      # Build the project
      - make ui-build VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION DOCKER_BUILDKIT=1
      # Push the image to ECR
      - make docker-push NAME=ui VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      # Scan the image for vulnerabilities with AWS ECR Image Scanning
      - make aws-ecr-get-security-scan REPOSITORY=ui TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION SHOW_ALL_WARNINGS=true
