# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  build:
    commands:
      # Run unit tests
      - make $UNIT_TEST_MAKE_TARGET
