apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: K8S_APP_NAMESPACE_TO_REPLACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: DOCKER_REGISTRY_TO_REPLACE/ui:VERSION_TO_REPLACE
          envFrom:
            - configMapRef:
                name: ui-configmap
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 7
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: "0.1"
              memory: "128M"
            limits:
              cpu: "1"
              memory: "1024M"
          imagePullPolicy: Always
