name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

permissions:
  security-events: write

jobs:
  CodeQL-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: typescript, python
          queries: security-and-quality
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
