name: "Check code for secrets"

on: push

permissions:
  actions: none
  checks: write
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: write

jobs:
  check-code-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if code contains any secrets
        run: |
          make \
            git-config \
            git-secrets-scan-repo-files
      - name: Checkov Secret Scan
        run: |
          make checkov-secret-scanning
