name: "General - Check code format and quality"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check text files format
        run: |
          build/automation/etc/githooks/scripts/editorconfig-pre-commit.sh
      - name: GitHub Actions - Check best practices
        run: |
          make github-actions-best-practices
      - name: Kubernetes - Check best practices
        run: |
          make kubernetes-best-practices
      - name: Docker - Check best practices
        run: |
          make docker-best-practices
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: application/ui/yarn.lock
      - name: Test Setup
        run: make typescript-test-ci-setup
      - name: Run Typescript Unit Tests
        run: make typescript-test
      - uses: sonarsource/sonarcloud-github-action@master
        # SEE: https://github.com/SonarSource/sonarcloud-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.sources=application,deployment,infrastructure
            -Dsonar.organization=nhsd-exeter
            -Dsonar.projectKey=uec-dos-ct
            -Dsonar.coverage.exclusions=**/__test__/**,deployment,infrastructure,application/ui/src/index.tsx,application/ui/jest.config.js,application/ui/craco.config.js
            -Dsonar.tests=test
            -Dsonar.terraform.provider.aws.version=4.48.0
            -Dsonar.python.version=3.9
            -Dsonar.javascript.lcov.reportPaths=application/ui/coverage/lcov.info
