name: "Python - Check code format and quality"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
jobs:
  test-check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            test/requirements-test.txt
      - name: Install Python Dependencies
        run: |
          make test-install
      - name: Python Import Format Check
        run: |
          make -s python-imports-check DIR="test"
      - name: Check Python Code Quality and Format
        run: |
          make -s python-code-check FILES="test"
