name: "Python - Check code format and quality"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            application/requirements-dev.txt
            application/*/requirements.txt
      - name: Python Install Requirements
        run: |
          make pip-install
      - name: Check Python Code Quality and Format
        run: |
          make -s python-code-check \
            FILES="." \
            EXCLUDE="application/ui,build"
      - name: Python Import Format Check
        run: |
          make python-imports-check
      - name: Python Dead Code Check
        run: |
          make python-dead-code-check
      - name: Python Security Check
        run: |
          make python-security-check

  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            application/requirements-dev.txt
            application/*/requirements.txt
      - name: Python Install Requirements
        run: make pip-install
      - name: Python Mutation Test
        run: |
          make python-mutation-test
      - name: Archive Test Results
        if: failure()
        run: |
          make python-mutation-test-report
