name: "Typescript - Check code format and quality"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Typescript Check Package
        run: |
          make typescript-package-duplicate-check

      - name: Typescript Code Format and Quality
        run: |
          make typescript-code-check
