name: "Typescript - Check code format and quality"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: application/ui/yarn.lock
      - name: Install dependencies
        run: make yarn-install
      - name: Typescript Check Package
        run: |
          make typescript-package-duplicate-check
      - name: Typescript Code Format and Quality
        run: |
          make typescript-check-format typescript-check-lint
  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: application/ui/yarn.lock
      - name: Install dependencies
        run: make yarn-install
      - name: Typescript Mutation Test
        run: |
          make typescript-mutation-test
